version: "3.8"

services:
  docs-dev-server:
    build:
      context: ../
      dockerfile: docker/images/Dockerfile.quickstart
    image: edb/docs-dev-server
    container_name: docs-dev-server
    hostname: docs-dev-server
    env_file:
      - ../.env.development
    init: true
    working_dir: /app
    command: >
      sh -c "npm run install-dependencies &&
      npm run develop -- -H 0.0.0.0 -p ${PORT:-8000} 2>&1"
    ports:
      - ${PORT:-8000}:${PORT:-8000}
    volumes:
      - ../:/app
